### ISSUE TITLE
`haskell-process-suggest-hoogle-imports` stopped working on ghc 7.8

### ISSUE THREAD

**Issue by bixuanzju** [haskell/haskell-mode#240]
The problem is, on ghc 7.8, the error message when something is out of scope would be, e.g.

> Not in scope: ‛getArgs’

Notice the curly single quotes around `getArgs`, which causes this [line](https://github.com/haskell/haskell-mode/blob/master/haskell-process.el#L687) to return `nil`.
